Lesson_7_task1 Генерация пароля
DenisKovalev1/KotlinSprint2024 pull request #15
Opened 2024-07-28 11:11 UTC by DenisKovalev1

2024-07-28 14:37 UTC, ievetrovdev requested changes

2024-07-28 14:37 UTC, ievetrovdev commented on src/main/kotlin/Lesson7/Lesson_7_task1.kt
> +        val charRange = ('a'..'z').random()
В своем решении ты создаешь диапазон при каждой итерации цикла. Давай зададим переменные с диапазоном чисел и диапазоном строк, а в цикле будем их использовать
PS: строго говоря, диапазон не создается, в Kotlin есть оптимизация, которая под капотом просто делает Random().nextInt(...), но все же

2024-07-28 14:48 UTC, DenisKovalev1 commented on src/main/kotlin/Lesson7/Lesson_7_task1.kt
> +        val charRange = ('a'..'z').random()
Ты имел ввиду так?

2024-07-29 07:02 UTC, ievetrovdev approved these changes
Да

2024-07-29 07:05 UTC, merged