Lesson_8_task4 Замена ингредиентов
DenisKovalev1/KotlinSprint2024 pull request #22
Opened 2024-07-28 16:33 UTC by DenisKovalev1

2024-07-28 23:48 UTC, ievetrovdev requested changes

2024-07-28 23:48 UTC, ievetrovdev commented on src/main/kotlin/Lesson8/Lesson_8_task4.kt
> +        val test = listIngredients.indexOf(userInput)
indexOf вернёт -1 если не найдёт элемент, давай не будем тогда проверять выше через in наличие элемента, чтобы уменьшить количество циклов поиска

2024-07-28 23:48 UTC, ievetrovdev commented on src/main/kotlin/Lesson8/Lesson_8_task4.kt
> +        listIngredients.set(test, tes)
Имена переменным нужно давать осмысленные

2024-07-29 20:03 UTC, ievetrovdev requested changes

2024-07-29 20:03 UTC, ievetrovdev commented on src/main/kotlin/Lesson8/Lesson_8_task4.kt
> +        val getIndex = listIngredients.indexOf(userInput)
listIngredients.indexOf уже выполняет тоже самое что listIngredients.contains. Если listIngredients.indexOf не найдет элемент, то вместо индекса вернется -1. Давай не будем делать поиск дважды, и обойдемся только использованием listIngredients.indexOf

2024-07-30 05:12 UTC, DenisKovalev1 commented on src/main/kotlin/Lesson8/Lesson_8_task4.kt
> +        val getIndex = listIngredients.indexOf(userInput)
Сейчас я еще сильнее запутался))

2024-09-14 19:26 UTC, ievetrovdev requested changes

2024-09-14 19:26 UTC, ievetrovdev commented on src/main/kotlin/Lesson8/Lesson_8_task4.kt
> +    if (getIndex == 1) {
indexOf вернет -1 если не найдет элемент, либо номер. Почему тут проверка на равенство единице?

2024-09-15 18:28 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-09-15 18:33 UTC, merged