Lesson_10_task3 Пароль через метод
DenisKovalev1/KotlinSprint2024 pull request #28
Opened 2024-08-02 09:35 UTC by DenisKovalev1

2024-08-02 09:44 UTC, ievetrovdev requested changes

2024-08-02 09:44 UTC, ievetrovdev commented on src/main/kotlin/Lesson10/Lesson_10_task3.kt
> +fun getPassword(lengthPassword: Int) {
Метод должен вернуть пароль, а не печатать на экране его

2024-08-02 11:30 UTC, DenisKovalev1 commented
Как сделать так что бы он выводил еще и не четное количество символов?

2024-08-02 20:51 UTC, ievetrovdev requested changes

2024-08-02 20:51 UTC, ievetrovdev commented on src/main/kotlin/Lesson10/Lesson_10_task3.kt
> +    for (i in 1..lengthPassword / 2) {
Попробуй вместо прохода до половины использовать взятие остатка от деления на 2(%). Это используй в условии, а цикл будет проходить всю длину пароля

2024-08-03 20:59 UTC, ievetrovdev approved these changes
Отличное решение, молодец!

2024-08-03 21:12 UTC, merged