Lesson_11_task2
DenisKovalev1/KotlinSprint2024 pull request #30
Opened 2024-08-03 15:52 UTC by DenisKovalev1

2024-08-04 14:59 UTC, ievetrovdev commented
Называть ветки кириллицей не лучшая практика. Гитхаб ее кодирует в читаемые символы о чем предупреждает
<img width="854" alt="Снимок экрана 2024-08-04 в 17 58 02" src="https://github.com/user-attachments/assets/d3262976-fd77-4003-8e2f-4a5d781669d4">

2024-08-04 15:00 UTC, ievetrovdev commented
По оформлению пулл реквеста:
 - Префикс проекта с названием и номером урока задачи следует прописывать в названии пулл реквеста. Например, "KS-1-1 сделал то-то".

2024-08-04 15:14 UTC, ievetrovdev requested changes

2024-08-04 15:14 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +
Пустая строка

2024-08-04 15:14 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +        val newBioRead = readln()
Промежуточную перемнную можно опустить

2024-08-04 15:14 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +    fun changePassword(inputpassword: String) {
В переменной на текущей строке содержится два слова. Предлагаю использовать стиль [lowerCamelCase](https://ru.wikipedia.org/wiki/CamelCase)

2024-08-06 18:25 UTC, ievetrovdev requested changes
Прошу обратить внимание на то, что название ветки написано на кириллице, что является не лучшей практикой.

2024-08-06 18:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +        Биография: $bio
А что будет выводится в консоль, если биография пустая. Как мы можем сделать, чтобы в консоль вывелось сообщение <нет информации>, если биография пустая ?

2024-08-06 18:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +            println("Введите новый пароль")
В ТЗ есть условие "сначала запросить текущий пароль"

2024-08-06 18:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +            password = newPasswordRead
Так же, согласно ТЗ, сообщаем пользователю, что пароль изменён

2024-08-06 18:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +    fun changePassword(inputPassword: String) {
Данная функция не должна принимать аргументы, в ней производится сравнение текущего пароля и нового, который ввёл пользователь

2024-08-06 18:25 UTC, ievetrovdev commented on src/main/kotlin/Lesson11/Lesson_11_task2.kt
> +        if (inputPassword == password) {
Перед выполнением блока If else, пользователю необходимо ввести новый пароль для дальнейшей проверки?

2024-08-11 18:19 UTC, DenisKovalev1 commented
https://github.com/DenisKovalev1/KotlinSprint2024/pull/30#issuecomment-2267572343

> Называть ветки кириллицей не лучшая практика. Гитхаб ее кодирует в читаемые символы о чем предупреждает <img alt="Снимок экрана 2024-08-04 в 17 58 02" width="854" src="https://private-user-images.githubusercontent.com/153023186/354910221-d3262976-fd77-4003-8e2f-4a5d781669d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MDA1ODYsIm5iZiI6MTcyMzQwMDI4NiwicGF0aCI6Ii8xNTMwMjMxODYvMzU0OTEwMjIxLWQzMjYyOTc2LWZkNzctNDAwMy04ZTJmLTRhNWQ3ODE2NjlkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxODE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjIzYzRjNDgxNjdhM2Q1YjY3MGI0NWJkY2M4YjY0ZDM0Y2E5NDIzNzFiMzM2MjYzYTFiYWE0NDA1ODQyMGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.io3SCXZtzkfY6zpQtVhQnuH7be3idUVZqN9nbAIKYwE">

А как переименовать на GitHab. В среде разработке переименовалось а тут как?

2024-09-23 10:28 UTC, ievetrovdev approved these changes
Переименовать ветку получится только создав новую вместо текущей и запишив ее

2024-09-23 13:08 UTC, merged