Lesson_13_task3 - Первый коммит. Telephone directory 3
DenisKovalev1/KotlinSprint2024 pull request #43
Opened 2024-08-14 17:54 UTC by DenisKovalev1

2024-08-14 20:15 UTC, ievetrovdev requested changes

2024-08-14 20:15 UTC, ievetrovdev commented on src/main/kotlin/Lesson13/Lesson_13_task3.kt
> +    users.forEach { it.informationOutput() }
В таком случае, одинаковые компании повторяются, попробуй исправить это через mapNotNull

2024-08-18 11:22 UTC, DenisKovalev1 commented
Или я тебя не правильно понял ?
Просто не совсем понимаю что изменилось?

2024-08-18 14:22 UTC, ievetrovdev requested changes

2024-08-18 14:22 UTC, ievetrovdev commented on src/main/kotlin/Lesson13/Lesson_13_task3.kt
> +    users.mapNotNull { it.informationOutput() }
По заданию требуется так: выведи список всех существующих компаний, которые есть в телефонной книге.

Тут выводится список контактов, а не компаний.

И важно что бы не было повторений одинаковых компаний из контактов. В данном случае просто немного надо доработать, а в целом направление верное!

2024-08-18 15:50 UTC, DenisKovalev1 commented
Работает. Но кажется мне что можно было все короче написать)

2024-08-19 14:41 UTC, ievetrovdev approved these changes
Принято, рабочее решение

2024-08-19 14:55 UTC, merged